services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DAILYMED_API_BASE_URL: ${DAILYMED_API_BASE_URL}
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
